/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "actczypotrjjzvgqdqlw"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFjdGN6eXBvdHJqanp2Z3FkcWx3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzA4NDI5NjIsImV4cCI6MjA4NjQxODk2Mn0.YOUR_ANON_KEY_HERE"
