/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "gfedfklnzkgifpdxrybh"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdmZWRma2xuemtnaWZwZHhyeWJoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzA4NDI5NjIsImV4cCI6MjA4NjQxODk2Mn0.JKVFpDT5YHpE9wgbDnJd7P-nTfD86Ov_T-ZPUyqStOs"